name: Deploy app

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build debug APK
        env:
          openweathermapApiKey: ${{ secrets.OPENWEATHERMAPAPIKEY }}
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 20
