name: Feature Branch CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  test:
    name: Run unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Unit test
      with:
        openweathermapApiKey: ${{ secrets.OPENWEATHERMAPAPIKEY }}
      run: bash ./gradlew testDebugUnitTest --stacktrace
