name: Feature Branch CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  test:
    name: Run unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Unit test
      env:
        openweathermapApiKey: ${{ secrets.OPENWEATHERMAPAPIKEY }}
      run: bash ./gradlew testDebugUnitTest --stacktrace
    - name: Print unit test report
      if: always()
      run: cat build/reports/tests/testDebugUnitTest/index.html
