name: Master branch push and merge requests

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: get API keys
        env:
          openweathermapApiKey: ${{ secrets.OPENWEATHERMAPAPIKEY }}
      - name: Unit test
        run: bash ./gradlew testDebugUnitTest --stacktrace
