name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Code analysis and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Detekt
        env:
          openweathermapApiKey: ${{ secrets.OPENWEATHERMAPAPIKEY }}
        run: bash ./gradlew detektAllModules
      - name: Unit test
        env:
          openweathermapApiKey: ${{ secrets.OPENWEATHERMAPAPIKEY }}
        run: bash ./gradlew testDebugUnitTest --stacktrace
